language: go

go:
  - '1.12.x'

env:
  global:
    - GO111MODULE=on

services:
  - docker

matrix:
  include:
    - script:
      - ./make-image.sh build all
      - go install
      - go test -timeout 0 -v ./tests

deploy:
- provider: script
  skip_cleanup: true
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" quay.io && ./make-image.sh push all
- provider: script
  skip_cleanup: true
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" quay.io && ./make-image.sh tag all $TRAVIS_TAG && ./make-image.sh push all $TRAVIS_TAG
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
