language: go

go:
  - '1.11.x'

env:
  global:
    - GO111MODULE=on

services:
  - docker

matrix:
  include:
    - script:
      - go test -timeout 0 -v ./tests

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
